spring:
  datasource:
    url: jdbc:mysql://lcoalhost:3306/o2o?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8080
  servlet:
    context-path: /
mybatis:
  type-aliases-package: com.rosam.springbootdatasourceconfig.entity
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    tk:
      mybatis: trace